name: L.Stadt
favicon: null
layout_spectrum: 0.04501
typography_spectrum: 0.55391
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0c0c2'
    - '#000000'
    - '#9d9ea2'
    - '#4b4a48'
    - '#6c6c6e'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
